import { Anonymous_Pro } from "next/font/google";
import "./globals.css";

const anon = Anonymous_Pro({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-anon'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anon.variable}`}>
        {children}
      </body>
    </html>
  );
}
